spring:
  application:
    name: OLX-Login
  config:
    import: "optional:configserver:http://localhost:8088" 
  datasource:
      url: jdbc:mysql://localhost:3306/olx_users
      username: root
      password: root
  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          ddl-auto: update
      show-sql: true
  